//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by StressEGD.rc
//
#define IDC_FIND_NEXT                   3
#define IDC_FOLDER_FUNCTION             3
#define IDC_PLC_CONNECT                 3
#define IDC_VP_LOAD                     3
#define IDC_SETUP_OK                    3
#define IDC_TAGEDIT_PASTE               3
#define IDC_FIND_GROUP                  4
#define IDC_PLC_EDIT                    4
#define IDC_SELECT_UPDATE               4
#define IDC_VP_SAVE                     4
#define IDC_SETUP_COLOR                 4
#define IDC_PLC_SETPLC                  5
#define IDC_FOLDER_COPY                 5
#define IDC_SETUP_CONNECT               6
#define IDC_PLC_DIAL                    6
#define IDC_SETUP_WIRING                7
#define IDC_SETUP_LOOPBACK              8
#define IDC_SETUP_DIAL                  9
#define IDM_NEW                         10
#define IDD_FNAME                       10
#define IDC_SETUP_HANGUP                10
#define IDM_OPEN                        11
#define IDM_COMPARE                     12
#define IDM_TO_ASCII                    13
#define IDM_FONT                        14
#define IDM_SAVE                        15
#define IDM_SAVEAS                      16
#define IDM_PAGE_SETUP                  17
#define IDM_PRINT                       18
#define IDM_EXIT                        19
#define IDM_UNDO                        20
#define IDM_CUT                         21
#define IDM_COPY                        22
#define IDM_PASTE                       23
#define IDM_CLEAR                       24
#define IDM_SELALL                      25
#define IDM_FIND                        30
#define IDM_NEXT                        31
#define IDM_REPLACE                     32
#define IDM_HELP                        50
#define IDM_ABOUT                       51
#define IDD_PLC_FOLDERS                 101
#define IDD_ABOUT_SETUP                 102
#define IDD_VERSA_IMP                   103
#define IDD_SETUP                       104
#define IDD_TAGNAMES                    105
#define IDD_TAGEDIT                     106
#define IDD_EGD_CONFIG                  107
#define IDD_BLOCKS                      108
#define IDD_SETUP_PLC                   109
#define IDD_ETHER_MON                   110
#define IDD_PLC_LIST                    111
#define IDD_TABLES                      112
#define IDD_FIND_ADDRESS                113
#define IDD_EGD_STRESS                  114
#define IDC_FIND_CONTACT                1000
#define IDC_FIND_COIL                   1001
#define IDC_FIND_EXPLICIT               1002
#define IDC_FIND_IMPLICIT               1003
#define IDC_FIND_SEARCH                 1004
#define IDC_FIND_BLOCKS                 1006
#define IDC_FOLDER_COPYTO               1007
#define IDC_FOLDER_COPYFROM             1008
#define IDC_FOLDER_DELETE               1010
#define IDC_FOLDER_LOCK                 1011
#define IDC_FOLDER_ZIP                  1012
#define IDC_FOLDER_DRIVE                1013
#define IDC_FOLDER_NAME                 1014
#define IDC_FOLDER_CREATE               1015
#define IDC_PLC_NUMBER                  1015
#define IDC_PLC_DESCRIPTION             1016
#define IDC_PLC_CPUID                   1017
#define IDC_PLC_TYPE                    1018
#define IDC_PLC_PORT                    1019
#define IDC_PLC_DATARATE                1020
#define IDC_PLC_FOLDER                  1020
#define IDC_PLC_PARITY                  1021
#define IDC_PLC_TCPIP                   1022
#define IDC_SETUP_TEXT                  1022
#define IDC_PLC_PHONE                   1023
#define IDC_SETUP_SCREEN                1023
#define IDC_PLC_CONN_TIME               1024
#define IDC_PLC_REQ_TIME                1025
#define IDC_PLC_TURN_TIME               1026
#define IDC_PLC_MULTIDROP               1027
#define IDC_SETUP_SPECIAL               1027
#define IDC_PLC_MODEMPC                 1028
#define IDC_PLC_STATUS                  1028
#define IDC_PLC_MODEMPLC                1029
#define IDC_PLC_LIST                    1029
#define IDC_PLC_NET_DATARATE            1029
#define IDC_VP_FOLDERS                  1032
#define IDC_VP_LABEL1                   1033
#define IDC_VP_LABEL2                   1034
#define IDC_VP_MERGE_TAGS               1035
#define IDC_VP_SAVE_COMMENT             1036
#define IDC_VP_LABEL3                   1037
#define IDC_SETUP_ALTR                  1040
#define IDC_SETUP_GRAPHIC               1041
#define IDC_SETUP_LOCAL                 1042
#define IDC_SETUP_REMOTE                1043
#define IDC_SETUP_STATUS                1044
#define IDC_SETUP_LOOP                  1045
#define IDC_SETUP_ONLINE                1046
#define IDC_SETUP_LOGIC64K              1047
#define IDC_SETUP_TYPE                  1048
#define IDC_SETUP_PROGRAM               1049
#define IDC_SETUP_FOLDERS               1050
#define IDC_VP_FIND                     1050
#define IDC_SETUP_BACKUPS               1051
#define IDC_TAG_ADDRESS                 1051
#define IDC_TAG_DESCRIPTION             1052
#define IDC_SETUP_WINDOW                1052
#define IDC_TAG_SAVE                    1053
#define IDC_TAG_LIST                    1054
#define IDC_TAG_SCROLL                  1055
#define IDC_TAG_CLEAR                   1056
#define IDC_TAG_LM90                    1057
#define IDC_TAG_BLOCKS                  1058
#define IDC_TAGEDIT_ADDRESS             1060
#define IDC_TAGEDIT_EDIT                1061
#define IDC_TAGEDIT_TAG                 1062
#define IDC_TAGEDIT_RET                 1063
#define IDC_TAGEDIT_TAGSIZE             1064
#define IDC_TAGEDIT_DESSIZE             1065
#define IDC_TAGEDIT_DES                 1066
#define IDC_TAGEDIT_VALSIZE2            1067
#define IDC_TAGEDIT_VAL                 1068
#define IDC_EGD_DEVICES                 1069
#define IDC_EGD_DETAILS                 1070
#define IDC_EGD_STATUS                  1071
#define IDC_EGD_MULTICAST               1072
#define IDC_EGD_ADDRESS                 1073
#define IDC_EGS_LABEL                   1074
#define IDC_EGD_TIMEOUT                 1075
#define IDC_PLC_PROGRAM                 1075
#define IDC_EGS_LABELT                  1076
#define IDC_PLC_CONFIG                  1076
#define IDC_EGD_GROUP                   1077
#define IDC_BLOCK_LIST                  1078
#define IDC_BLOCK_SELECT                1079
#define IDC_BLOCK_REFUSED               1080
#define IDC_BLOCK_LIBRARY               1081
#define IDC_BLOCK_SELECTED              1082
#define IDC_PRINT_LOGIC                 1083
#define IDC_PRINT_INLINE                1084
#define IDC_PRINT_VALUES                1085
#define IDC_PRINT_USAGE                 1086
#define IDC_PRINT_TAGNAMES              1087
#define IDC_PRINT_XREF                  1088
#define IDC_BLOCK_NEWNAME               1089
#define IDC_PRINT_DESCR                 1090
#define IDC_BLOCK_DESCR                 1091
#define IDC_PRINT_COMMENTS              1092
#define IDC_BLOCK_PRINT                 1093
#define IDC_BLOCK_TEMPLATE              1094
#define IDC_BLOCK_VIEW                  1095
#define IDC_BLOCK_2LIBRARY              1096
#define IDC_BLOCK_SIDEFILE              1097
#define IDC_ABOUT_SETUP                 1098
#define IDC_BLOCK_LOCK                  1099
#define IDC_ETHER_PLC                   1100
#define IDC_ETHER_SCANPLC               1101
#define IDC_ETHER_PORT                  1102
#define IDC_ETHER_SHOW                  1103
#define IDC_ETHER_TASKB                 1104
#define IDC_ETHER_TASKC                 1105
#define IDC_ETHER_TASKF                 1106
#define IDC_ETHER_TASKG                 1107
#define IDC_ETHER_TASKH                 1108
#define IDC_ETHER_TASKI                 1109
#define IDC_ETHER_TASKJ                 1110
#define IDC_ETHER_TASKL                 1111
#define IDC_ETHER_TASKR                 1112
#define IDC_ETHER_TASKU                 1113
#define IDC_ETHER_TASKV                 1114
#define IDC_ETHER_TASKW                 1115
#define IDC_ETHER_STAT                  1116
#define IDC_ETHER_TALLY                 1117
#define IDC_ETHER_TRACE                 1118
#define IDC_ETHER_CLEAR                 1119
#define IDC_ETHER_MONITOR               1120
#define IDC_ETHER_COMMAND               1121
#define IDC_ETHER_NODE                  1122
#define IDC_ETHER_RECORD                1123
#define IDC_ETHER_PING                  1124
#define IDC_ETHER_LOG                   1125
#define IDC_ETHER_TEXT                  1126
#define IDC_ETHER_CHANNEL               1127
#define IDC_ETHER_CHANNUM               1128
#define IDC_ETHER_CHANSPIN              1129
#define IDC_LIST_FILE                   1130
#define IDC_LIST_LOAD                   1131
#define IDC_PLC_SPIN                    1132
#define IDC_LIST_UPDATE                 1133
#define IDC_LIST_DELETE                 1134
#define IDC_LIST_EGD                    1135
#define IDC_LIST_TYPE                   1137
#define IDC_TABLE_LIST                  1137
#define IDC_TABLE_WORD                  1138
#define IDC_TABLE_INT                   1139
#define IDC_TABLE_LONG                  1140
#define IDC_TABLE_REAL                  1141
#define IDC_TABLE_HEX                   1142
#define IDC_TABLE_BIT                   1143
#define IDC_TABLE_ASCII                 1144
#define IDC_TABLE_TIMER                 1145
#define IDC_TABLE_FORCE                 1146
#define IDC_TABLE_TOGGLE                1147
#define IDC_TABLE_READ                  1148
#define IDC_TABLE_EDIT                  1149
#define IDC_TABLE_MIXED                 1150
#define IDC_TABLE_OVERRIDES             1151
#define IDC_TABLE_INPUT                 1152
#define IDC_TABLE_ADDRESS               1153
#define IDC_TABLE_TAGNAME               1155
#define IDC_TABLE_DATA                  1156
#define IDC_TABLE_SCROLL                1157
#define IDC_TABLE_RETENTIVE             1158
#define IDC_EGD_RESET                   1159
#define IDC_EGD_CLOSE                   1160
#define IDC_EGD_ADJUST_PERIOD           1161
#define IDC_EGD_TO_DEVICE               1162
#define IDC_EGD_PERIOD                  1163
#define IDC_EGD_BYTES                   1164
#define IDC_EGD_PING                    1165
#define IDC_EGD_SAVE                    1166
#define IDC_EGD_LIST                    1167
#define IDM_LOGIC                       40002
#define IDM_VARIABLES                   40003
#define IDM_TAGNAMES                    40003
#define IDM_PRINT_PREVIEW               40007
#define IDM_LAST_FILE1                  40008
#define IDM_LAST_FILE2                  40009
#define IDM_LAST_FILE3                  40010
#define IDM_LAST_FILE4                  40011
#define IDM_GOTO                        40012
#define IDM_TABLES                      40013
#define IDM_STATUS                      40014
#define IDM_CONFIG                      40015
#define IDM_BLOCKS                      40017
#define IDM_VIEW_TAGNAMES               40018
#define IDM_COMPRESS_RUNGS              40019
#define IDM_SHOW_DATA                   40020
#define IDM_DESCRIPTIONS                40021
#define IDM_PLC_FOLDERS                 40029
#define IDM_VERSA_IMP                   40032
#define IDM_EGD_CONFIG                  40033
#define IDM_SETUP                       40034
#define IDM_MERGE_TAGS                  40035
#define IDM_COMMENTS                    40037
#define IDM_TRANSFER                    40038
#define IDM_ETHERNET_REQ                40040
#define IDM_GENIUS_REQ                  40041
#define IDM_CCM_REQ                     40042
#define IDM_SNP_REQ                     40043
#define IDM_SVC_REQ                     40044
#define IDM_HSC_REQ                     40045
#define IDM_SAVE_TAGS                   40046
#define IDM_LOAD_COMMENTS               40047
#define IDM_SAVE_COMMENTS               40048
#define IDM_CONTENTS                    40049
#define IDM_INDEX                       40050
#define IDM_SEARCH                      40051
#define IDM_TECH_SUPPORT                40052
#define IDM_FAQ                         40054
#define IDM_SOFTWARE_UPDATES            40055
#define IDM_ETHER_MON                   40056
#define IDM_PLC_LIST                    40057
#define IDM_DEL_FILE                    40058
#define IDM_TABLE_RIGHT_LEFT            40059
#define IDM_TABLE_LINE_SPACERS          40060
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         40062
#define _APS_NEXT_CONTROL_VALUE         1168
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
